.TH "LCD_DrawPropTypeDef" 3 "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
LCD_DrawPropTypeDef
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <bsp_lcd\&.h>\fP
.SS "成员变量"

.in +1c
.ti -1c
.RI "uint32_t \fBTextColor\fP"
.br
.ti -1c
.RI "uint32_t \fBBackColor\fP"
.br
.ti -1c
.RI "sFONT * \fBpFont\fP"
.br
.in -1c
.SH "结构体成员变量说明"
.PP 
.SS "uint32_t LCD_DrawPropTypeDef::BackColor"

.SS "sFONT* LCD_DrawPropTypeDef::pFont"

.SS "uint32_t LCD_DrawPropTypeDef::TextColor"


.SH "作者"
.PP 
由 Doyxgen 通过分析 My Project 的 源代码自动生成\&.
